# -*- coding: utf-8 -*-
"""streamlit_run

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWvSGt4L5JM53n3_jFMVgn2IY1w4oh0O
"""

!pip install streamlit -q
!pip install tabula-py -q
!pip install pinecone -q
!pip install sentence_transformers -q
!pip install pdfplumber -q

!wget -q -O - ipv4.icanhazip.com

! streamlit run frontend_qabot.py & npx localtunnel --port 8501



